### ISSUE TITLE
setting

### ISSUE THREAD

**Issue by foXaCe** [iFelix18/Trakt-Userscripts#1]
hello,

After installation, enter your OMDb API Key in the script settings.

how to please or Screenshots 

thank you

**Comment by iFelix18** [comment]
The script settings should appear automatically when it is activated, that is when you visit a movie or a series page, **if the api key is not present**.
Does not it appear by visiting a movie page (for example on [this](https://trakt.tv/movies/back-to-the-future-1985))? If it does not appear automatically it is a issue that I will have to solve.

Alternatively, you can recall the settings from your script manager.
On Tampermonkey, for example:
![Tampermonkey](https://user-images.githubusercontent.com/19800006/53132443-fe8ff500-356f-11e9-8e0c-1dc09778b299.jpg)

**Comment by foXaCe** [comment]
hello, yes it appears when I go on a film page
thank you
