### ISSUE TITLE
Ratings not woking

### ISSUE THREAD

**Issue by azumukupoe** [iFelix18/Trakt-Userscripts#10]
below is my config
```
  GM_config.init({
    'id': 'MyConfig',
    'title': 'Ratings on Trakt - Settings',
    'fields': {
      'apikey': {
        'label': 'OMDb API Key',
        'section': ['You can request a free OMDb API Key at:', 'https://www.omdbapi.com/apikey.aspx'],
        'type': 'text',
        'default': '123312b9'
      }
    },
    'events': {
      'save': function () {
        alert('Ratings on Trakt: Settings saved')
        location.reload()
      }
    }
  })
```

**Comment by iFelix18** [comment]
This should be why it doesn't work:
> ``` diff
>   GM_config.init({
>     'id': 'MyConfig',
>     'title': 'Ratings on Trakt - Settings',
>     'fields': {
>       'apikey': {
>         'label': 'OMDb API Key',
>         'section': ['You can request a free OMDb API Key at:', 'https://www.omdbapi.com/apikey.aspx'],
>         'type': 'text',
> -       'default': '123312b9'
> +       'default': ''
>       }
>     },
>     'events': {
>       'save': function () {
>         alert('Ratings on Trakt: Settings saved')
>         location.reload()
>       }
>     }
>   })
> ```

You don't need to change the code to enter your API key, but it must be entered it in the script settings.
On Tampermonkey, for example:
![Tampermonkey](https://user-images.githubusercontent.com/19800006/53132443-fe8ff500-356f-11e9-8e0c-1dc09778b299.jpg)

**Comment by azumukupoe** [comment]
It doesn't work on Firefox with VIolentmonkey

**Comment by iFelix18** [comment]
Update the script to the version [2.3.2](https://github.com/iFelix18/Trakt-Userscripts/raw/e41855e345d67beffe4bed86629907babc306872/userscripts/ratings-on-trakt.user.js), should fix the problem. Let me know if it works.

**Comment by azumukupoe** [comment]
yet i see no ratings on trakt
I got the setting working for ratings but not translate fyi

**Comment by iFelix18** [comment]
> I got the setting working for ratings but not translate fyi

I need to update soon the other scripts to make the settings on Violentmonkey work.

> yet i see no ratings on trakt

Don't you see the ratings? In the script settings, check the "Logging" option, open the console (Ctrl+Shift+K on Firefox), go to a movie page, and tell me what it shows relative to the "Ratings on Trakt" script.

**Comment by azumukupoe** [comment]
```
Ratings on Trakt: CSS added index.html:156:15
Ratings on Trakt: OMDb API Key is "123312b9" index.html:156:15
Ratings on Trakt: IMDb ID is "tt0080455"
```
the Translate script works by the way

**Comment by iFelix18** [comment]
For me with Firefox v68.0.2, Violentmonkey v2.11.2 and Ratings on Trakt v2.3.3 works perfectly. It should show you this:
```
Ratings on Trakt v2.3.3 by Felix is running!
Ratings on Trakt: CSS added
Ratings on Trakt: OMDb API Key is "xxxxxxx"
Ratings on Trakt: IMDb ID is "tt0080455"
Ratings on Trakt: IMDb rating is "7.9"
Ratings on Trakt: IMDb votes is "168.9k"
Ratings on Trakt: IMDb rating added
Ratings on Trakt: Tomatometer is "83%"
Ratings on Trakt: Tomatometer rating added
Ratings on Trakt: Metascore is "60"
Ratings on Trakt: Metascore rating added
```

Do you have a valid api key?

**Comment by azumukupoe** [comment]
The translate script seems to be incompatible with the ratings script for me

**Comment by iFelix18** [comment]
All scripts are now updated and working with Violentmonkey. 

Are you still having issues? Check that you have the latest version.
