### ISSUE TITLE
GM_config causes a conflict between all scripts

### ISSUE THREAD

**Issue by memnos** [iFelix18/Trakt-Userscripts#147]
Hello,
starting from last update if i install all scripts, it keeps me asking to config all plugins one after another forever.
While if i uninstall ratings script all seems ok.
I'm using Chrome.
I tried both violentmonkey and tampermonkey with the same result.
What can i do?

**Comment by iFelix18** [comment]
I should have solved it. You need to update all scripts.
Tell me if the issue still occurs now.

**Comment by memnos** [comment]
Know i'm not asked config continously, but ratings seems not to work.

**Comment by memnos** [comment]
It does not work even if i enable only ratings script

**Comment by iFelix18** [comment]
This could be caused by a different problem than the one that was causing the configuration request.

Please open a new issue. Enable Logging and Debugging in the Ratings on Trakt settings, and tell me what the console shows.
