### ISSUE TITLE
Rating script doesn't work

### ISSUE THREAD

**Issue by memnos** [iFelix18/Trakt-Userscripts#148]
I've installed ratings script, but when i enter a movie i see no ratings.

**Console Logs**
The log is in the attached file

**Desktop (please complete the following information):**
 - Browser Chrome
 - Userscript manager Tampermonkey
 - Userscript manager version v3.2.2
 
[trakt.tv-1644097729457.log](https://github.com/iFelix18/Trakt-Userscripts/files/8008976/trakt.tv-1644097729457.log)

**Comment by iFelix18** [comment]
Update the script to [3.2.3](https://github.com/iFelix18/Trakt-Userscripts/commit/6a07a9845406ffa7d3e0dab0879829149a2df8df) and try again.

**Comment by memnos** [comment]
Perfect, now all seems ok.
Tnx
