### ISSUE TITLE
Traslation of title and poster

### ISSUE THREAD

**Issue by memnos** [iFelix18/Trakt-Userscripts#26]
Hello,
i don't know if i make anything wrong, but i see poster and title translated only from inside the movie, but, for example, if i am in history i see poster and titles in English.
Is there anything i can do to have translations also there?
I know that with Trakt improver i have translation also in history.
Tnx

**Comment by iFelix18** [comment]
Yeah, this is deliberate, the translation takes place only in the movies/series/season/episode detail pages, not in the other pages of Trakt, at the moment.

But, maybe, I can add it in a future update of the script.

**Comment by memnos** [comment]
OK, thank you so much.
For the moment i'll use both.

**Comment by iFelix18** [comment]
Done, [3.0.0](https://github.com/iFelix18/Trakt-Userscripts/commit/d029cfa87258bc0e9272d23d519b01bdbbce38e2).

In this version a Trakt API Key is now required.

**Comment by memnos** [comment]
Nice, it is working fine.
tnx
