### ISSUE TITLE
Ability to save filters

### ISSUE THREAD

**Issue by Kenifornication** [iFelix18/Trakt-Userscripts#38]
Hi

Thank you for making these scripts, I kind of missed these features when my VIP expired (me poor). I wonder if it is possible to add the ability to save filters (the calendar filters, in particular) like the VIPs. I suppose GM can save local values, so you're just storing the filter arguments.

I need this because I kind of use complicated filters, one for English speaking shows, one for French... etc, to discover new shows.

I would appreciate it immensely if you could add this. Thank you.

**Comment by Kenifornication** [comment]
Did the script stop working altogether?

**Comment by Kenifornication** [comment]
@iFelix18 Did the script stop working altogether?

**Comment by iFelix18** [comment]
> 
> 
> @iFelix18 Did the script stop working altogether?

Yeah, it doesn't work at the moment, Trakt has changed its site structure. I will look for an alternative way in the near future, if possible.
