### ISSUE TITLE
Advanced Filtering on Trakt doesn't work

### ISSUE THREAD

**Issue by SonOfDiablo** [iFelix18/Trakt-Userscripts#40]
Hello, 

I know this issue is already noted in this comment: https://github.com/iFelix18/Trakt-Userscripts/issues/38#issuecomment-580167938 
However I thought I would start a new issue as to not pollute the other issue further.  

Actually I just wanted to know if there was any updates on the process of a fix?

**Comment by iFelix18** [comment]
No updates at the moment, and i'm busy lately, but any help is welcome.
