### ISSUE TITLE
Feature request: Rottentomatoes scores for TV shows?

### ISSUE THREAD

**Issue by dairefagan** [iFelix18/Trakt-Userscripts#63]
Please consider implementing Rottentomatoes scores for TV shows.

**Comment by iFelix18** [comment]
The ratings are provided by the OMDb API, which, for TV series, only provides IMDb rating.

**Comment by i486** [comment]
Any plan on adding Metacritic on trakt tv shows? What about TMDB api? Does it provide metacritic link?
