### ISSUE TITLE
Stats: not working since v3

### ISSUE THREAD

**Issue by Kenifornication** [iFelix18/Trakt-Userscripts#99]
Hi,

I like what you did with the stats script, looks more useful than the old version (from what the screenshots show), however I couldn't get the visuals to show (the stats don't show up where they used to show, nothing at all). I added the client ID correctly and there are no errors in the console. I'm on Windows 10, Chrome 92, using Tampermonkey v4.13.

Could you look into it, please? Thank you.

**Comment by iFelix18** [comment]
Hi,
I've tested it on Windows 10, Chrome 92, and Tampermonkey v4.13, and everything works fine.

Stats are not shown on any show page? Check the _Logging_ and _Debugging_ options in the script settings, and let me know what appears in the browser console.

**Comment by Kenifornication** [comment]
Well this is embarrassing, turns out it was just a CSS snafu on my part. I'm very sorry for bothering you with this. Thank you for making these scripts, they have been very useful. :)
